on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: suilteam/cxy:latest-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          apk add sqlite-dev
          cxy package install --verbose
          cxy package build --verbose
